# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsdog < Formula
  desc "A command line tool to debug and explore WebSocket."
  homepage "https://github.com/ylgrgyq/wsdog"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.4/wsdog_Darwin_x86_64.tar.gz"
      sha256 "7d7619a39a4a1becc5e9bfca23fd849ebe7c39abf03c0604bde9b7e035ae2505"

      def install
        bin.install "wsdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.4/wsdog_Linux_x86_64.tar.gz"
      sha256 "595499fa6b2cb2d7472d79f4175fdb1c81afe7ccd0f64fece14f0fda2ba81829"

      def install
        bin.install "wsdog"
      end
    end
  end

  test do
    system "#{bin}/wsdog -v"
  end
end
