# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsdog < Formula
  desc "A command line tool to debug and explore WebSocket."
  homepage "https://github.com/ylgrgyq/wsdog"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.3/wsdog_Darwin_x86_64.tar.gz"
    sha256 "f1c62a966e8a34545a9b44b9b0797b7b1986a0ccee09713840d83c23a2528049"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.3/wsdog_Linux_x86_64.tar.gz"
    sha256 "dce769295846f6c45a20b8b6d80608dc68f9c36e66fde4a5326899db0609c5d3"
  end

  def install
    bin.install "wsdog"
  end

  test do
    system "#{bin}/wsdog -v"
  end
end
