# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsdog < Formula
  desc "A command line tool to debug and explore WebSocket."
  homepage "https://github.com/ylgrgyq/wsdog"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.2/wsdog_Darwin_x86_64.tar.gz"
    sha256 "54d96523a815471a251b017add43a0e0546b9bdabe7bdce2bf3454a09c916ea9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ylgrgyq/wsdog/releases/download/v1.0.2/wsdog_Linux_x86_64.tar.gz"
    sha256 "3786817d8d759de52de0ac03e472360721715c5efff7da821debfa84d4558152"
  end

  def install
    bin.install "wsdog"
  end

  test do
    system "#{bin}/wsdog -v"
  end
end
